[[services]]
name = "customer-site"
source = "apps/customer-site"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["apps/customer-site/**"]

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm start"

[[services]]
name = "dealer-portal"  
source = "apps/dealer-portal"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["apps/dealer-portal/**"]

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm start"